--- 
engines: 
  csslint: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - javascript
    enabled: true
  eslint: 
    enabled: true
  golint: 
    enabled: true
  rubocop: 
    enabled: true
exclude_paths: 
  - build/**/*
  - doc/**/*
  - examples/**/*
  - external/**/*
  - licenses-3rd/**/*
  - shaders/**/*
  - tests/**/*
  - tutorials/**/*
  - Mizar.min.js
  - "**.png"
  - "**.jpg"
  - "**.jpeg"
ratings: 
  paths: 
    - src/**