engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  golint:
   	enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- build/**
- doc/**
- examples/**
- external/**
- licenses-3rd/**
- shaders/**
- tests/**
- tutorials/**
- "Mizar.min.js"
- "**.png"
- "**.jpg"
- "**.jpeg"
